### ISSUE TITLE
Cats Rights!!!!

### ISSUE THREAD

**Issue by dnscat** [Entytaiment25/meowping#11]
My lovely Dear,

sadly I've found a small problem with your beautiful program.
Sadly the cat does not get displayed right.

Proof of the issue:
![image](https://github.com/Entytaiment25/meowping/assets/119243145/a43dbf86-615e-4cb8-9975-e91acce41e4c)

**Comment by Entytaiment25** [comment]
Win10 cmd is affected

**Comment by tempusernamedduck** [comment]
Windows be like: :trollface:

**Comment by tempusernamedduck** [comment]
Works in: Win10 Terminal (console, pwsh), Win11 Terminal (console, pwsh)
Doesn't work in: Win10 (standard/old) cmd/pwsh
